     <?php
     // This mapping the icon w/ it's tag, so Nucleus can replace the icon in run-time
     $emoticons = array(
                  ':wink:' => 'icon_wink.gif',
                  ':lol:' => 'icon_lol.gif',
                  ':cry:' => 'icon_cry.gif',
                  ':evil:' => 'icon_evil.gif',
                  ':twisted:' => 'icon_twisted.gif',
                  ':roll:' => 'icon_rolleyes.gif',
                  ':idea:' => 'icon_idea.gif',
                  ':arrow:' => 'icon_arrow.gif',
                  ':mrgreen:' => 'icon_mrgreen.gif',
                  ':-)' => 'icon_smile.gif',
                  ':)' => 'icon_smile.gif',
                  ':-(' => 'icon_sad.gif',
                  ':(' => 'icon_sad.gif',
                  ';-)' => 'icon_wink.gif',
                  ';)' => 'icon_wink.gif',
                  ':!:' => 'icon_exclaim.gif',
                  ':?:' => 'icon_question.gif',
                  ':oops:' => 'icon_redface.gif',
                  ':o' => 'icon_surprised.gif',
                  ':-D' => 'icon_biggrin.gif',
                  ':D' => 'icon_biggrin.gif',
                  '8O' => 'icon_eek.gif',
                  '8)' => 'icon_cool.gif',
                  ':?' => 'icon_confused.gif',
                  ':x' => 'icon_mad.gif',
                  ':P' => 'icon_razz.gif',
                  ':|' => 'icon_neutral.gif'
                );

?>
