     <?php
     // This mapping the icon w/ it's tag, so Nucleus can replace the icon in run-time
     $emoticons = array(
                  '[smile]' => 'icon_smile.gif',
                  '[confused]' => 'icon_confused.gif',
                  '[cool]' => 'icon_cool.gif',
                  '[cry]' => 'icon_cry.gi',
                  '[eek]' => 'icon_eek.gif',
                  '[angry]' => 'icon_angry.gif',
                  '[sweat]' => 'icon_sweat.gif',
                  '[lol]' => 'icon_lol.gif',
                  '[razz]' => 'icon_razz.gif',
                  '[music]' => 'icon_music.gif',
                  '[heart]' => 'icon_heart.gif',
                  '[sad]' => 'icon_sad.gif',
                  '[egg]' => 'icon_egg.gif',
                  '[fd]' => 'icon_fd.gif',
                  '[ft]' => 'icon_ft.gif',
                  '[lovely]' => 'icon_lovely.gif',
                  '[question]' => 'icon_question.gif',
                  '[shame]' => 'icon_shame.gif',
                  '[fluke]' => 'icon_fluke.gif',
                  '[tongue]' => 'icon_tongue.gif'
                );
?>
